### PR TITLE
New blend

### PR DESCRIPTION
**Pull request by wlbragg**
This added a new blend file for blender (#1) and new exported .ac file. Added some missing rgb textures trying to track down the hidden gauges at certain angles. #5 Issue was not fixed.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I will test it now.

**Comment by gilbertohasnofb** [comment]
Gosh, I thought I was in the c172p repository testing the propeller spinner fix hence the silly labels :blush: Anyway, I will test this (and that other PR as well)

**Comment by gilbertohasnofb** [comment]
@wlbragg perfect, thanks a lot! 
@awall086 from now on, let's sue the .blend file inside the folder `/Models` for any modifications, okay?

**Comment by awall086** [comment]
I found a solution for #5 issue. Replacing VacFace object in blend file, and exporting for create a new .ac file. I tried the solution tonight and it worked correctly. I suspect it may be related to the use of scale animation to enlarge or reduce the size of the instrument.

I will apply the same solution to other instruments having the same problem.

**Comment by gilbertohasnofb** [comment]
@wlbragg once Adrian implements this would you help checking it out? You know so much more about this kind of things than I do

**Comment by wlbragg** [comment]
Yes, I'll check it out.

**Comment by gilbertohasnofb** [comment]
@wlbragg thank you!

**Pull request merged**
